gpu_cache:
  enable: true
  set_size: 1024
  set_associativity: 2
  block_size: 64
  slab_size: 32

ps_cache:
  enable: true
  set_size: 1024
  set_associativity: 2
  block_size: 64
  slab_size: 32

file_cache:
  enable: false
  set_size: 1024
  set_associativity: 2
  block_size: 64
  slab_size: 32
  cache_dir: "./cache_dir"